parameters:
    google_analytics.class: GoogleAnalytics\Lib\Tracker

services:
    google_analytics:
        class: %google_analytics.class%
        arguments:    [ %google_analytics.accountID% , %google_analytics.domain% ]