parameters:
    google_analytics.tracker: Kairos\GoogleAnalytics\Tracker

services:
    google_analytics:
        class: %google_analytics.tracker%
        arguments:    [ %php_ga_accountID% , %php_ga_domain% ]